spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot
    password: ${POSTGRESQL_PASSWORD}
    username: ${POSTGRESQL_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  main:
    allow-bean-definition-overriding: true